#!/bin/bash
. $CCCDIR/usr/bin/$CCCUNAME/__unix.b
build.exe @ccc.bld #'BUILD_DBG=on'

mkdir $CCCDIR/usr/lib/$CCCBIN 2>/dev/null
cp -pf $BUILD_OBJ/*.lib    $CCCDIR/usr/lib/$CCCBIN
#cp -pf $BUILD_OBJ/*.so     $CCCDIR/usr/lib/$CCCBIN
 

#so kozvetlen cp helyett mv-vel kerul a helyere,
#hogy az eppen futo programok nem szalljanak el
find $BUILD_OBJ/*.so | while read so; do
    cp -pf $so $so.new
    mv $so.new  $CCCDIR/usr/lib/$CCCBIN/`basename $so`
done

