#!/bin/bash
#set -x
#echo `pwd`

bapp_unix0.b  -d. -dunix  -i../sckutil -sccc2_sslsocket  -bssl

cp -pf obj$CCCBIN/*.lib  $CCCDIR/usr/lib/$CCCBIN
#cp -pf obj$CCCBIN/*.so  $CCCDIR/usr/lib/$CCCBIN
cp -pf ssl.ch  $CCCDIR/usr/include

#so kozvetlen cp helyett mv-vel kerul a helyere,
#hogy az eppen futo programok nem szalljanak el
for so in obj$CCCBIN/*.so; do
    cp -pf $so $so.new
    mv $so.new  $CCCDIR/usr/lib/$CCCBIN/`basename $so`
done
