#define LOWPRECEDENCE                   1
#define UNEXPECTEDCHAR                  2
#define NL                              3
#define DOT                             4
#define DOTDOT                          5
#define COMMA                           6
#define ASSIGN                          7
#define ADDASS                          8
#define SUBASS                          9
#define MULASS                         10
#define DIVASS                         11
#define MODASS                         12
#define COLCOLASS                      13
#define OR                             14
#define AND                            15
#define NOT                            16
#define EQ                             17
#define EQEQ                           18
#define GTEQ                           19
#define LTEQ                           20
#define EXEQ                           21
#define GT                             22
#define LT                             23
#define DOLLAR                         24
#define PLUS                           25
#define MINUS                          26
#define STAR                           27
#define SLASH                          28
#define MODULO                         29
#define DBSTAR                         30
#define PIPE                           31
#define DBPLUS                         32
#define DBMINUS                        33
#define LBRACKET                       34
#define COLON                          35
#define COLCOL                         36
#define ARROW                          37
#define HIGHPRECEDENCE                 38
#define NAMESPACE                      39
#define USING                          40
#define SYMBOL                         41
#define STATIC                         42
#define CLANG                          43
#define LPAR                           44
#define RPAR                           45
#define CLASS                          46
#define STCLASS                        47
#define NEW                            48
#define ATTRIB                         49
#define METHOD                         50
#define FUNCTION                       51
#define STFUNCTION                     52
#define LOCAL                          53
#define QUIT                           54
#define RETURN                         55
#define END                            56
#define WHILE                          57
#define FOR                            58
#define TO                             59
#define LOOP                           60
#define EXIT                           61
#define BEGSEQ                         62
#define RECOVER                        63
#define FINALLY                        64
#define IF                             65
#define DOCASE                         66
#define CASE                           67
#define ELSEIF                         68
#define ELSE                           69
#define OTHERWISE                      70
#define STEP                           71
#define RBRACKET                       72
#define AT                             73
#define NUMBER                         74
#define STRING                         75
#define NLSTEXT                        76
#define STRINGX                        77
#define TRUE                           78
#define FALSE                          79
#define NIL                            80
#define LBRACE                         81
#define RBRACE                         82
