#define LOWPRECEDENCE                   1
#define UNEXPECTEDCHAR                  2
#define NL                              3
#define DOT                             4
#define DOTDOT                          5
#define COMMA                           6
#define ASSIGN                          7
#define ADDASS                          8
#define SUBASS                          9
#define MULASS                         10
#define DIVASS                         11
#define MODASS                         12
#define COLCOLASS                      13
#define OR                             14
#define AND                            15
#define NOT                            16
#define EQ                             17
#define EQEQ                           18
#define GTEQ                           19
#define LTEQ                           20
#define EXEQ                           21
#define GT                             22
#define LT                             23
#define DOLLAR                         24
#define PLUS                           25
#define MINUS                          26
#define STAR                           27
#define SLASH                          28
#define MODULO                         29
#define DBSTAR                         30
#define DBPLUS                         31
#define DBMINUS                        32
#define LBRACKET                       33
#define COLON                          34
#define COLCOL                         35
#define ARROW                          36
#define HIGHPRECEDENCE                 37
#define NAMESPACE                      38
#define USING                          39
#define SYMBOL                         40
#define STATIC                         41
#define CLANG                          42
#define LPAR                           43
#define RPAR                           44
#define CLASS                          45
#define STCLASS                        46
#define NEW                            47
#define ATTRIB                         48
#define METHOD                         49
#define FUNCTION                       50
#define STFUNCTION                     51
#define LOCAL                          52
#define QUIT                           53
#define RETURN                         54
#define END                            55
#define WHILE                          56
#define FOR                            57
#define TO                             58
#define LOOP                           59
#define EXIT                           60
#define BEGSEQ                         61
#define RECOVER                        62
#define FINALLY                        63
#define IF                             64
#define DOCASE                         65
#define CASE                           66
#define ELSEIF                         67
#define ELSE                           68
#define OTHERWISE                      69
#define STEP                           70
#define RBRACKET                       71
#define AT                             72
#define NUMBER                         73
#define STRING                         74
#define NLSTEXT                        75
#define STRINGX                        76
#define TRUE                           77
#define FALSE                          78
#define NIL                            79
#define LBRACE                         80
#define PIPE                           81
#define RBRACE                         82
