#define LOWPRECEDENCE                   1
#define UNEXPECTEDCHAR                  2
#define NL                              3
#define DOT                             4
#define DOTDOT                          5
#define COMMA                           6
#define ASSIGN                          7
#define ADDASS                          8
#define SUBASS                          9
#define MULASS                         10
#define DIVASS                         11
#define MODASS                         12
#define COLCOLASS                      13
#define OR                             14
#define AND                            15
#define NOT                            16
#define EQ                             17
#define EQEQ                           18
#define GTEQ                           19
#define LTEQ                           20
#define EXEQ                           21
#define GT                             22
#define LT                             23
#define DOLLAR                         24
#define PLUS                           25
#define MINUS                          26
#define STAR                           27
#define SLASH                          28
#define MODULO                         29
#define DBSTAR                         30
#define DBPLUS                         31
#define DBMINUS                        32
#define LBRACKET                       33
#define COLON                          34
#define COLCOL                         35
#define ARROW                          36
#define HIGHPRECEDENCE                 37
#define NAMESPACE                      38
#define USING                          39
#define SYMBOL                         40
#define STATIC                         41
#define LPAR                           42
#define RPAR                           43
#define CLASS                          44
#define STCLASS                        45
#define NEW                            46
#define ATTRIB                         47
#define METHOD                         48
#define FUNCTION                       49
#define STFUNCTION                     50
#define LOCAL                          51
#define QUIT                           52
#define RETURN                         53
#define END                            54
#define WHILE                          55
#define FOR                            56
#define TO                             57
#define LOOP                           58
#define EXIT                           59
#define BEGSEQ                         60
#define RECOVER                        61
#define FINALLY                        62
#define IF                             63
#define DOCASE                         64
#define CASE                           65
#define ELSEIF                         66
#define ELSE                           67
#define OTHERWISE                      68
#define STEP                           69
#define RBRACKET                       70
#define AT                             71
#define NUMBER                         72
#define STRING                         73
#define NLSTEXT                        74
#define STRINGX                        75
#define TRUE                           76
#define FALSE                          77
#define NIL                            78
#define LBRACE                         79
#define PIPE                           80
#define RBRACE                         81
