#!/bin/bash
bapp_unix0.b  -sccc2_sql2_postgres

cp -pf obj$CCCBIN/*.lib  $CCCDIR/usr/lib/$CCCBIN
#cp -pf obj$CCCBIN/*.so   $CCCDIR/usr/lib/$CCCBIN
cp -pf sql.ch  $CCCDIR/usr/include

#so kozvetlen cp helyett mv-vel kerul a helyere,
#hogy az eppen futo programok nem szalljanak el
for so in obj$CCCBIN/*.so; do
    cp -pf $so $so.new
    mv $so.new  $CCCDIR/usr/lib/$CCCBIN/`basename $so`
done
 